Repository VirtusLab/akka-serialization-helper, pull requests merged in 2021-09, with the labels that each got.

#80 Added disable feature for registration checker plugin
  registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/RegistrationCheckerCompilerPlugin.scala
Labels: enhancement

#85 Added checks in CirceAkkaSerializer against NullPointerExceptions
  circe-akka-serializer/src/main/scala/org/virtuslab/ash/circe/CirceAkkaSerializer.scala
Labels: soundness

#89 Make scalafix actually remove the unused imports
  build.sbt
  circe-akka-serializer/src/test/scala/org/virtuslab/ash/circe/data/ModifiedCodec.scala
  circe-akka-serializer/src/test/scala/org/virtuslab/ash/circe/data/StdMigration.scala
  dump-event-schema-compiler-plugin/src/test/scala/org/virtuslab/ash/compiler/DumpEventSchemaCompiler.scala
  registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/RegistrationCheckerCompilerPlugin.scala
  registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala
  sbt-dump-event-schema/src/main/scala/org/virtuslab/ash/DumpEventSchema.scala
  serializability-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponentSpec.scala
Labels: code

#90 Serializability checker ignores types serialized by Akka internal serializers
  serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala
  serializability-checker-compiler-plugin/src/test/resources/AkkaSerializabilityTraitsTest.scala
  serializability-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponentSpec.scala
Labels: bug

#91 Changed format of schema dump from json to yaml
  build.sbt
  project/Dependencies.scala
  sbt-dump-event-schema/src/main/scala/org/virtuslab/ash/DumpEventSchema.scala
  sbt-dump-event-schema/src/main/scala/org/virtuslab/ash/model/DumpEventSchemaJsonProtocol.scala
  sbt-dump-event-schema/src/main/scala/org/virtuslab/ash/model/Field.scala
  sbt-dump-event-schema/src/main/scala/org/virtuslab/ash/model/TypeDefinition.scala
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.AdditionalData.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.ClassTest.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.ClassWithAdditionData.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.DeepTrait.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.DeeperTrait.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.DeepestClass.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.GenericsTest.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.TraitWithAnnotation.json
  sbt-dump-event-schema/src/test/resources/example-jsons/org.random.project.Data.json
  sbt-dump-event-schema/src/test/resources/target.yaml
  sbt-dump-event-schema/src/test/scala/org/virtuslab/ash/DumpEventSchemaSpec.scala
Labels: usability

#93 Bumped scala, sbt and libraries versions
  examples/event-migration/project/build.properties
  project/Dependencies.scala
  project/build.properties
  project/plugins.sbt
  sbt-dump-event-schema/src/sbt-test/sbt-dumpschema/simple/build.sbt
  sbt-dump-event-schema/src/sbt-test/sbt-dumpschema/simple/project/build.properties
Labels: enhancement

#95 Added Akka persistent states to schema dump
  build.sbt
  dump-event-schema-compiler-plugin/src/main/resources/scalac-plugin.xml
  dump-persistence-schema-compiler-plugin/src/main/resources/scalac-plugin.xml
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/CrossVersionReporter.scala
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/DumpPersistenceSchemaCompilerPlugin.scala
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/DumpPersistenceSchemaCompilerPluginComponent.scala
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/DumpPersistenceSchemaOptions.scala
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/model/Field.scala
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/model/TypeDefinition.scala
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/writer/DumpPersistenceSchemaJsonProtocol.scala
  dump-persistence-schema-compiler-plugin/src/main/scala/org/virtuslab/ash/writer/PersistenceSchemaWriter.scala
  dump-persistence-schema-compiler-plugin/src/test/resources/AbstractTrigger.scala
  dump-persistence-schema-compiler-plugin/src/test/resources/Data.scala
  dump-persistence-schema-compiler-plugin/src/test/resources/DataEnum.scala
  dump-persistence-schema-compiler-plugin/src/test/resources/GenericTrigger.scala
  dump-persistence-schema-compiler-plugin/src/test/resources/StateData.scala
  dump-persistence-schema-compiler-plugin/src/test/resources/Trigger.scala
  dump-persistence-schema-compiler-plugin/src/test/scala/org/virtuslab/ash/DumpPersistenceSchemaCompilerPluginComponentSpec.scala
  dump-persistence-schema-compiler-plugin/src/test/scala/org/virtuslab/ash/PersistenceSchemaWriterSpec.scala
  dump-persistence-schema-compiler-plugin/src/test/scala/org/virtuslab/ash/compiler/DumpPersistenceSchemaCompiler.scala
  sbt-dump-event-schema/src/main/scala/org/virtuslab/ash/DumpEventSchemaPlugin.scala
  sbt-dump-event-schema/src/sbt-test/sbt-dumpschema/simple/build.sbt
Labels: event/state compatibility

#99 Renamed registration-checker-compiler-plugin
  build.sbt
  codec-registration-checker-compiler-plugin/src/main/resources/scalac-plugin.xml
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/ClassSweepCompilerPluginComponent.scala
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/CodecRegistrationCheckerCompilerPlugin.scala
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/CodecRegistrationCheckerOptions.scala
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala
  codec-registration-checker-compiler-plugin/src/test/resources/data/GenericData.scala
  codec-registration-checker-compiler-plugin/src/test/resources/data/IndirectData.scala
  codec-registration-checker-compiler-plugin/src/test/resources/data/Register.scala
  codec-registration-checker-compiler-plugin/src/test/resources/data/SerializableTrait.scala
  codec-registration-checker-compiler-plugin/src/test/resources/data/StdData.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/CorrectSerializer.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/EmptySerializer.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/IncompleteSerializer.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/InvalidAnnotationSerializer.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/InvalidClassSerializer.scala
  codec-registration-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/CodecRegistrationCheckerCompiler.scala
  codec-registration-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/CodecRegistrationCheckerCompilerPluginSpec.scala
  codec-registration-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/Data.scala
  registration-checker-compiler-plugin/src/main/resources/scalac-plugin.xml
  registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/RegistrationCheckerOptions.scala
  sbt-ash/src/main/scala/org/virtuslab/ash/AkkaSerializationHelperKeys.scala
  sbt-ash/src/main/scala/org/virtuslab/ash/AkkaSerializationHelperPlugin.scala
  sbt-ash/src/sbt-test/sbt-dumpschema/simple/build.sbt
Labels: code quality

#103 Rename sbt-ash to sbt-akka-serialization-helper
  .sbtopts
  build.sbt
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/AkkaSerializationHelperKeys.scala
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/AkkaSerializationHelperPlugin.scala
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/DumpPersistenceSchema.scala
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/model/DumpPersistenceSchemaJsonProtocol.scala
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/model/Field.scala
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/model/TypeDefinition.scala
  sbt-akka-serialization-helper/src/sbt-test/sbt-dumpschema/simple/build.sbt
  sbt-akka-serialization-helper/src/sbt-test/sbt-dumpschema/simple/project/build.properties
  sbt-akka-serialization-helper/src/sbt-test/sbt-dumpschema/simple/project/plugins.sbt
  sbt-akka-serialization-helper/src/sbt-test/sbt-dumpschema/simple/src/main/scala/Data.scala
  sbt-akka-serialization-helper/src/sbt-test/sbt-dumpschema/simple/src/main/scala/Triggers.scala
  sbt-akka-serialization-helper/src/sbt-test/sbt-dumpschema/simple/test
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.AdditionalData.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.ClassTest.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.ClassWithAdditionData.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.DeepTrait.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.DeeperTrait.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.DeepestClass.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.GenericsTest.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.TraitWithAnnotation.json
  sbt-akka-serialization-helper/src/test/resources/example-jsons/org.random.project.Data.json
  sbt-akka-serialization-helper/src/test/resources/target.yaml
  sbt-akka-serialization-helper/src/test/scala/org/virtuslab/ash/DumpPersistenceSchemaSpec.scala
Labels: distribution
