Repository VirtusLab/akka-serialization-helper, pull requests merged in 2022-07, with the labels that each got.

#180 fixed logic of `collectMissingClassNames`
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala
  codec-registration-checker-compiler-plugin/src/test/resources/data/NestedData.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/CorrectSerializer.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/EmptySerializer.scala
  codec-registration-checker-compiler-plugin/src/test/resources/serializers/IncompleteSerializerTwo.scala
  codec-registration-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/CodecRegistrationCheckerCompilerPluginSpec.scala
Labels: bug, codecs

#181 make registration regex more universal
  circe-akka-serializer/src/main/scala/org/virtuslab/ash/circe/Register.scala
Labels: codecs, soundness

#183 Refactor false positives fix
  README.md
  build.sbt
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/CacheFileInteractionMode.scala
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/CodecRegistrationCheckerCompilerPlugin.scala
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/CodecRegistrationCheckerOptions.scala
  codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala
  codec-registration-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/CodecRegistrationCheckerCompilerPluginSpec.scala
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/AkkaSerializationHelperKeys.scala
  sbt-akka-serialization-helper/src/main/scala/org/virtuslab/ash/AkkaSerializationHelperPlugin.scala
Labels: code quality, codecs

#200 Refatcor from tuple to case class
  serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala
Labels: code quality

#205 Fix false positives for Actor System usage
  build.sbt
  project/Dependencies.scala
  serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala
  serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala
  serializability-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponentSpec.scala
Labels: bug, soundness

#209 Adding .scala-steward.conf file
  .scala-steward.conf
Labels: build, ci

#211 Fix path to scala-steward build root
  .scala-steward.conf
Labels: bug, build

#207 Added GUIDE.md file
  README.md
  circe-akka-serializer/src/main/scala/org/virtuslab/ash/circe/Register.scala
  docs/GUIDE.md
Labels: docs
